### ISSUE TITLE
Account does not exist. Please fund your account with free testnet Mina from the faucet.

### ISSUE THREAD

**Issue by johnshearing** [t4top/mina-wordle-game#6]
Greetings,
Thank you for making this wonderful Mina example.

I am getting the following error when attempting to input a word.
`Account does not exist. Please fund your account with free testnet Mina from the faucet.`

But as seen below I have a wallet connected.
![image](https://github.com/t4top/mina-wordle-game/assets/22293905/72996401-1b8b-466c-9eff-15a3373d8dad)
Would you please tell me how to proceed?

Much thanks

**Comment by t4top** [comment]
You are getting this error because `snarkyjs.fetchAccount()` request to the Mina berkeley testnet failed. This project uses `snarkyjs@0.7.3`, which is now outdated. Current berkeley testnet uses `snarkyjs@0.10.1`. There was a name change of `sequence state` to `action state` introduced in [PR #764](https://github.com/o1-labs/snarkyjs/pull/764) which was a breaking change. In order to fix this issue, I'll need to upgrade the dependencies of this project and re-deploy.

**Comment by johnshearing** [comment]
Thank you for your response @t4top,
Yes please, I would be grateful if you would update the dependencies.
This is truly the most complete turnkey example of Mina I have seen and I have really looked to see what is out there.
It is one of only two with a working UI that I have been able to find and the only one that uses an oracle.
Much thanks for the education.

**Comment by t4top** [comment]
I'm really delighted that you found the project useful. I'll update the dependencies during the weekend.

**Comment by johnshearing** [comment]
Greetings t4top<
I just tried to use the wordle app again.
The same error is produced.
Of course you know this already because you have this marked as WIP.
So the only reason I am writing now is to show my interest and to say thank you for the work you are doing.
Best regards, John

**Comment by t4top** [comment]
Thanks John for your interest in the project. Though the PR is still WIP, the reported issue is already resolved in the `version-up` branch. You can clone the repo into a new directory, checkout the `version-up` branch and give it a try.

**Comment by johnshearing** [comment]
Yes, @t4top,
It is working on the version-up branch.
I can't wait to see how it all works.
Thank you so much for this example.
